# Generated by Django 4.0.3 on 2022-07-24 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_alter_todo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('c', 'COMPLETED'), ('p', 'PENDING')], max_length=2),
        ),
    ]
