# Generated by Django 4.0.3 on 2022-07-26 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_alter_todo_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='Email',
        ),
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('p', 'PENDING'), ('c', 'COMPLETED')], max_length=2),
        ),
    ]
